// <auto-generated />
namespace Pagers_Search_Filters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Stepone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stepone));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131804206_Step one "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
